### PR TITLE
Removed WPRO plugin for Amazon S3 and Cloudfront plugin

### PR DESCRIPTION
**Pull request by rttsai**
WPRO is outdated does not work in the latest version of WordPress

### CODE REVIEW

**Comment by xyu** [comment]
@rttsai are you seeing errors when using WPRO / can you elaborate on what is not working?

In addition we can not simply remove WPRO without replacing its functionality as we would lose the ability to upload images / attachments. If we are to remove WPRO we should have to do something like #29.

**Comment by rttsai** [comment]
@xyu - I can't quite remember the issues I was having, but I believe the images simply weren't being uploaded to my Amazon S3 bucket. And if you view the page source, the images were still being loaded from my WordPress server.

If you look at my commit, I removed WPRO and replaced it with Amazon S3 and Cloudfront, which is exactly what @tomcastleman suggested in https://github.com/xyu/heroku-wp/issues/29.

**Comment by alexkravets** [comment]
+1 `WP Offload S3` also provides a configuration to serve files from S3 via https

**Comment by xyu** [comment]
I think before we can pull this we need to write some backwards compatible code to move WPRO settings into the AWS plugin so we don't break any sites that was using WPRO.

**Comment by xyu** [comment]
Closing this because Heroku WP now comes with https://github.com/humanmade/S3-Uploads by default instead.

**Pull request closed without merging**
