### PR TITLE
Update init.sh

### PR DESCRIPTION
**Pull request by tcastelli**
Solved Errors without " random generate special characters that have to be escaped or double quoted

### CODE REVIEW

**Comment by xyu** [comment]
Thanks for the PR! How about we add the double quotes but keep it a single `heroku config:set` command? That would make it easier to do rollbacks and keep the Heroku history cleaner.

**Comment by tcastelli** [comment]
Sure, the only problem is when I tried with a single heroku config:set with bash on windows 10 it was not working. But maybe it works with normal bash have you tried?

**Comment by xyu** [comment]
Hmm I see I'm on Mac OS and doing a single set seems to work correctly I don't have a Windows box to test this though...

```
➜  heroku-wp git:(app/xyu.io) ✗ heroku config:set \
>   --app "***" \
>   WP_AUTH_KEY="$(         dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )" \
>   WP_SECURE_AUTH_KEY="$(  dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )" \
>   WP_LOGGED_IN_KEY="$(    dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )" \
>   WP_NONCE_KEY="$(        dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )" \
>   WP_AUTH_SALT="$(        dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )" \
>   WP_SECURE_AUTH_SALT="$( dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )" \
>   WP_LOGGED_IN_SALT="$(   dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )" \
>   WP_NONCE_SALT="$(       dd "if=/dev/random" "bs=1" "count=96" 2>/dev/null | base64 )"
Setting WP_AUTH_KEY, WP_SECURE_AUTH_KEY, WP_LOGGED_IN_KEY, WP_NONCE_KEY, WP_AUTH_SALT, WP_SECURE_AUTH_SALT, WP_LOGGED_IN_SALT, WP_NONCE_SALT and restarting ⬢ ***... done, v185
WP_AUTH_KEY:         uh8mvH3hdpuKHTyAKLxHwQ8Aoof2NjiV0VYUYA2Xj78OMhzUkCT9iB8kwSdajtq/xeDQjwgMEj3lO/hUzb4RL+WuHTJKIEMe4/jKsAtI5CeijUUta4W+QWZXG2SBKvjT
WP_AUTH_SALT:        rwN4wig6bZHiMreMT14URHlA6EZ2Gz5YXPgnb8Duk25Ry34eb0UJmaPFzTfG6UJdcUDdbE0k9JdT0yAxbvUE7gCgqIhS13ZCjFY/uGxSGIsAPGS0K2uiny1Lb9RDDYyd
WP_LOGGED_IN_KEY:    iluwvAGR8+z0PSgZ0nLZ3myAeW0D4Q98uaSmdy5Ft0vSm6DuVJJ1EE6jvifFmBHAVgGRA9GY+3mQL9hUyN3aZiPE3mkvZCD7gX7nkEp1vbkWQ6IiJHsD1UcW4TELHxrb
WP_LOGGED_IN_SALT:   +AS3RsCzxEsPO9kwWLYL388EW2K5+rpNUwJYOtOp3oKDUokT9mT+qZOHBQIbXWPz0D7AbkaewYdkKHlYRC4TMuLUbfJnp9lqqFSrkaS5phAdpxfWAIVyM/K8H5ICWhDk
WP_NONCE_KEY:        SbPK2jQFnr3ftNFoyv4ku1AQRdwXfN8gN7IrOK4yIS9Kwn7fLLFJbxka3KfpdBtrrMSpRoGeowNvRAoWN8fl9DwrfYpKnChHO2Yj+1Vs1lcqlMRyhnWXjP87nAgfzOAp
WP_NONCE_SALT:       KsmiGtrM9JoMc8Wqb7NMoGvysq1cROSLWFtZ68JZqaLW+AMXhNh1gVKEhmG1LP5IY+TNNiEQHIeKfx2oox6vqcyaU4uxAdOPVAKpn2425OH+CF0Iquj01yP9EkcEjX2I
WP_SECURE_AUTH_KEY:  bB9/jBIhyk/0sLwnDOYqVGIk4F/RkzJghzwVcpydc2JNiZDjEZc3YEPK7H/Hx1NDVwj4OYL2QygUfvDDJZIsCNpsz2KZBSc5ZYsnED7lypu1MYDqyLo5tiDFKQ8wEohe
WP_SECURE_AUTH_SALT: TQu0/dkfFU/ybGmBnr/GxuvLE+U2qIvldycbXCZRu5aJHSn1u1PlHbTRkTWvnqrRyzMrgkbjoTYHf1iBwkSf8eIQjN8c2C/tCm/D7fDGoAn8fB3D94GMbvoHxdjTW8l3
```

**Comment by xyu** [comment]
Maybe it's the double quotes that's messing Windows Bash up? perhaps this would be better:

```
heroku config:set \
	--app "$1" \
	WP_AUTH_KEY="$(         dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
	WP_SECURE_AUTH_KEY="$(  dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
	WP_LOGGED_IN_KEY="$(    dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
	WP_NONCE_KEY="$(        dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
	WP_AUTH_SALT="$(        dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
	WP_SECURE_AUTH_SALT="$( dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
	WP_LOGGED_IN_SALT="$(   dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
	WP_NONCE_SALT="$(       dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )"
```

Still works on Mac OS:

```
➜  heroku-wp git:(app/xyu.io) ✗ heroku config:set \
>       --app "***" \
>       WP_AUTH_KEY="$(         dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
>       WP_SECURE_AUTH_KEY="$(  dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
>       WP_LOGGED_IN_KEY="$(    dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
>       WP_NONCE_KEY="$(        dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
>       WP_AUTH_SALT="$(        dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
>       WP_SECURE_AUTH_SALT="$( dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
>       WP_LOGGED_IN_SALT="$(   dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )" \
>       WP_NONCE_SALT="$(       dd 'if=/dev/random' 'bs=1' 'count=96' 2>/dev/null | base64 )"
Setting WP_AUTH_KEY, WP_SECURE_AUTH_KEY, WP_LOGGED_IN_KEY, WP_NONCE_KEY, WP_AUTH_SALT, WP_SECURE_AUTH_SALT, WP_LOGGED_IN_SALT, WP_NONCE_SALT and restarting ⬢ ***... done, v188
WP_AUTH_KEY:         8MWJq/6zxwyBOhM1sdU+gOxxl5ap3kqTe0KfOE4U1Ir5hVk1i7bVhU+FW889wiXJu32vAbA7qNpYRe2lUX7hYbNKUAiotPn/bQ6OpZ52v3oFOQg3pRX6ZX20cY+G/k4v
WP_AUTH_SALT:        RHkjCtaVUbveAtceCoSF95fswkeLRPiFNJ6Ks3mutUwUVHlQoFHyB64gKNta3TcLKm8hYdU30P0/qRIEwkuWxpQIvvOm4wjgupm4W5lQ7yTgUkeUCwkeya0TO0nlnUzt
WP_LOGGED_IN_KEY:    VKnF7TCdt+UJlEkLWfLuBRYWxdX667716BN0dx3Frxo88c/F9uLrQWC86GiU0v+2682TyZYpEj8gYCjLWQ5aa+1cSETdv0K1tm5o1wdW2hOR7dRZ3An+JC8OQHQe5CHC
WP_LOGGED_IN_SALT:   XUM7v39WAZ8F90SHG5gg7ya6ZGmJEODsLiOgFIh2Oe1pomvj6ZpxCnfqlPm+W8h5RmwLCYFH+dWpskrZ46BTvVRzeoRFR5WCfbW1XLP/74MIHU/L6O4Rh6sRLxspPqwa
WP_NONCE_KEY:        o8eraaLTxDyk43cBOlDW5IYcGad7KTV4Bi80NF7ih5bye8nSwkhIF7Uqi0unclrAN1y3Yqd5s6Pdsr5f3A87JlvZ7gUv6wyAipqzNLlPcJaUb5V/1HsFRxKPv/WRU2aC
WP_NONCE_SALT:       DXKFqNHmT9R5gNM03C6Dgn92Sdh9NDZig5gBRuu7Md5eZmfM3DfjnDVwBNRSE+CIqwykbLb9dWN4TysmFjY9/BBGlvBb83IJktWguXzdms8jZF3wRaguz1eToQIOxhsu
WP_SECURE_AUTH_KEY:  28lN/dtB97/LKU3oC7TqD8Dz8LjTPGsA6FuKQ47Q+jkQXaw7APNqEkpcOzjRWlkmLq2Na44Zvx/4kuoPajGjLGN9hStTD8RG4ipDSMSKaOQ4EA5R4dV2tYC14+ZmwqTh
WP_SECURE_AUTH_SALT: vkSLGbFlYMkGQ8Jjs6n0IeBuz3FWlM2UdaWG3jmBHuHZqqa5P9YqmP023lOjD/YfQ8RSZge6pOrz0obzDsjHWdDOFyquSs13BrS9OIVwNAWHomg1/Okb6Y93pWJeOz6C
```

**Comment by tcastelli** [comment]
I think it's working okay right now on windows VM, so I must have changed something else that was making single set config not work when I tried the first time.

Anyway since the chage its simple you can go on ;)

**Pull request closed without merging**
